name: Run Trading Bot

on:
  schedule:
    #- cron: '0,30 4-10 * * 1-5'  # Every 30 minutes from 9:30 to 3:30 IST (Mon-Fri)
    - cron: '*/5 * * * *'  # Every 5 minutes (for testing)
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python main.py
